version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "===== PRE-BUILD STAGE ====="
      - echo "Region: $AWS_REGION"
      - echo "Account ID: $AWS_ACCOUNT_ID"
      - echo "Repository URL: $ECR_REPO_URL"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL

  build:
    commands:
      - echo "===== BUILD STAGE ====="
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_URL:$IMAGE_TAG .
      - echo "Tagging image for ECR..."
      - docker tag $ECR_REPO_URL:$IMAGE_TAG $ECR_REPO_URL:$IMAGE_TAG

  post_build:
    commands:
      - echo "===== POST-BUILD STAGE ====="
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URL:$IMAGE_TAG
      - echo "Generating imagedefinitions.json for ECS deploy..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$ECR_REPO_URL:$IMAGE_TAG" > imagedefinitions.json
      - echo "===== Image Definitions File ====="
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
